rtiAddress = localhost:8989
federationName = SEE 2026
federateName = Rover_Federate
federateType = Vehicle
federateRole = late
lookahead = 1000000
asynchronousDelivery = false
timeRegulating = true
timeConstrained = true
# Only uncomment the following line if you have any FOM module extensions. All your FOM modules are to be placed in the
# directory mentioned below.
# fomDirectory = src/main/resources/foms/